figures:
  # Graph #1
  - name: graph1_L1_missrate_vs_log2L1_by_ASSOC
    title: "Graph #1 — L1 Miss Rate vs log2(L1 Size) by Associativity (gcc_trace)"
    x: log2_L1_SIZE
    y: L1_miss_rate
    series: assoc_label          
    hold:
      trace: gcc.trace.txt
      BLOCKSIZE: 32
      L2_SIZE: 0
      L2_ASSOC: 0
      PREF_N: 0
      PREF_M: 0
      sweep: graph1_size_assoc

  # Graph #2 (exclude FA)
  - name: graph2_AAT_vs_log2L1_by_ASSOC_noFA
    title: "Graph #2 — AAT vs log2(L1 Size) by Associativity (no FA)"
    x: log2_L1_SIZE
    y: amat
    series: assoc_label          # show series by assoc
    hold:
      trace: gcc.trace.txt
      BLOCKSIZE: 32
      L2_SIZE: 0
      L2_ASSOC: 0
      PREF_N: 0
      PREF_M: 0
      sweep: graph1_size_assoc

  # Graph #3
  - name: graph3_AAT_vs_log2L1_by_ASSOC_L2_16KB_8way
    title: "Graph #3 — AAT vs log2(L1 Size) with L2=16KB, 8-way"
    x: log2_L1_SIZE
    y: amat
    series: assoc_label
    hold:
      trace: gcc.trace.txt
      BLOCKSIZE: 32
      L2_SIZE: 16384
      L2_ASSOC: 8
      PREF_N: 0
      PREF_M: 0
      sweep: graph3_l2

  # Graph #4
  - name: graph4_L1_missrate_vs_log2BLOCK_by_L1SIZE_A4
    title: "Graph #4 — L1 Miss Rate vs log2(BLOCKSIZE) by L1 Size (A=4)"
    x: log2_BLOCKSIZE
    y: L1_miss_rate
    series: L1_SIZE
    hold:
      trace: gcc.trace.txt
      L1_ASSOC: 4
      L2_SIZE: 0
      L2_ASSOC: 0
      PREF_N: 0
      PREF_M: 0
      sweep: graph4_blocksize

  # Graph #5
  - name: graph5_AAT_vs_log2L1_by_L2SIZE
    title: "Graph #5 — AAT vs log2(L1 Size) by L2 Size (A_L1=4, A_L2=8)"
    x: log2_L1_SIZE
    y: amat
    series: L2_SIZE
    hold:
      trace: gcc.trace.txt
      BLOCKSIZE: 32
      L1_ASSOC: 4
      L2_ASSOC: 8
      PREF_N: 0
      PREF_M: 0
      sweep: graph5_l2size
