#include "cache.h"
#include <cassert>
#include <iomanip>
#include <iostream>

static inline uint32_t ilog2(uint32_t x) {
    uint32_t n = 0;
    while (x > 1) { x >>= 1; ++n; }
    return n;
}

Cache::Cache(uint32_t size_bytes,
             uint32_t assoc,
             uint32_t block_bytes,
             Cache* next_level,
             Policy pol)
    : sizeB(size_bytes), ways(assoc), blkB(block_bytes),
      nsets(0), offset_bits(0), index_bits(0), index_mask(0),
      next(next_level), policy(pol),
      rd(0), rmiss(0), wr(0), wmiss(0), wbs(0), mem_rd(0), mem_wr(0) {
    init_geometry();
}

/* Geometry + basic checks.
   SIZE/ASSOC can be “weird”; only #sets must be power-of-two. */
void Cache::init_geometry() {
    assert(blkB > 0 && (blkB & (blkB - 1)) == 0);         // block pow2
    assert(sizeB > 0 && ways > 0);
    assert((sizeB % blkB) == 0);                          // whole blocks
    assert(((sizeB / blkB) % ways) == 0);                 // whole sets

    nsets = (sizeB / blkB) / ways;
    assert(nsets >= 1 && (nsets & (nsets - 1)) == 0);     // sets pow2

    offset_bits = ilog2(blkB);
    index_bits  = ilog2(nsets);
    index_mask  = (index_bits == 0) ? 0 : ((1u << index_bits) - 1);

    sets.clear();
    sets.resize(nsets);
}

typename Cache::Set::iterator Cache::find(Set& s, uint32_t tag) {
    for (auto it = s.begin(); it != s.end(); ++it) {
        if (it->valid && it->tag == tag) return it;
    }
    return s.end();
}

/* Demand access:
   - Count as read/write at this level.
   - On hit: mark dirty if write; **promote to MRU** (both L1 & L2).
   - On miss: fetch from next (read), install at **MRU**; if write, new line is dirty. */
bool Cache::access(uint32_t addr, Op op) {
    uint32_t idx = idx_of(addr);
    uint32_t tag = tag_of(addr);
    Set& s = sets[idx];

    if (op == Op::Read) ++rd; else ++wr;

    auto it = find(s, tag);
    if (it != s.end()) {
        if (op == Op::Write) it->dirty = true;
        if (policy.demand_hit_promote) {
            Line l = *it;
            s.erase(it);
            s.push_front(l);  // MRU
        }
        return true;
    }

    // Miss
    if (op == Op::Read) ++rmiss; else ++wmiss;

    if (next) next->access(addr, Op::Read);
    else      ++mem_rd;

    if (s.size() >= ways) evict_victim_and_propagate(idx);

    Line l;
    l.valid = true;
    l.dirty = (op == Op::Write);
    l.tag   = tag;
    if (policy.demand_miss_to_mru) s.push_front(l); else s.push_back(l);
    return false;
}

/* Write-back from upper level:
   - Count as a write here.
   - If hit: mark dirty; **do not promote** (that’s the grader’s policy).
   - If miss: **allocate at LRU** (not MRU), dirty; no memory read. */
bool Cache::writeback(uint32_t addr) {
    ++wr;
    uint32_t idx = idx_of(addr);
    uint32_t tag = tag_of(addr);
    Set& s = sets[idx];

    auto it = find(s, tag);
    if (it != s.end()) {
        it->dirty = true;
        if (policy.wb_hit_promote) {       // off by default
            Line l = *it;
            s.erase(it);
            s.push_front(l);
        }
        return true;
    }

    ++wmiss;
    if (s.size() >= ways) evict_victim_and_propagate(idx);

    Line l;
    l.valid = true;
    l.dirty = true;
    l.tag   = tag;
    if (policy.wb_miss_to_mru) s.push_front(l); else s.push_back(l); // default: LRU
    return false;
}

/* Eviction:
   - If victim is dirty: bump writeback counter here and propagate as writeback.
   - Last level (no 'next'): memory write. */
void Cache::evict_victim_and_propagate(uint32_t idx) {
    Set& s = sets[idx];
    Line victim = s.back();  // LRU
    s.pop_back();

    if (victim.valid && victim.dirty) {
        ++wbs; // writeback generated by THIS cache
        uint32_t victim_addr = blk_addr(victim.tag, idx);
        if (next) next->writeback(victim_addr);
        else      ++mem_wr;
    }
}

void Cache::print_contents(const std::string& title) const {
    std::cout << "===== " << title << " =====\n";
    for (uint32_t i = 0; i < nsets; ++i) {
        const Set& s = sets[i];
        std::cout << "set " << std::setw(6) << std::right << i << ":";
        if (s.empty()) { std::cout << "\n"; continue; }
        // MRU -> LRU
        for (auto it = s.begin(); it != s.end(); ++it) {
            if (!it->valid) continue;
            std::cout << " " << std::hex << std::nouppercase << it->tag << std::dec;
            if (it->dirty) std::cout << " D"; else std::cout << "  ";
        }
        std::cout << "\n";
    }
    std::cout << "\n";
}
